import { Unbounded } from 'next/font/google';
import { ReactNode } from 'react';

import './globals.css';
import { Navbar } from '../components';

const unbounded = Unbounded({ weight: '600', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen ${unbounded.className}`}>
        <Navbar />
        <header></header>
        <main>{children}</main>
      </body>
    </html>
  );
}
